language: node_js
node_js:
  - "6"
  - "8"
  - "10"

env:
  - NODE_ENV=development

before_install:
  - npm i -g npx

cache:
  directories:
    - "node_modules"

script:
  - npm run build
  - npm test
  - npx codecov

notifications:
  email: false
